<?php

namespace App\Helpers\SidoohNotify;


use App\Helpers\Sidooh\USSD\Entities\BasicEnum;

abstract class EventTypes extends BasicEnum
{
    const DEFAULT = "DEFAULT";
    const TEST = "TEST";

    const AIRTIME_PURCHASE = "AIRTIME_PURCHASE";
    const AIRTIME_PURCHASE_FAILURE = "AIRTIME_PURCHASE_FAILURE";

    const UTILITY_PAYMENT = "UTILITY_PAYMENT";
    const UTILITY_PAYMENT_FAILURE = "UTILITY_PAYMENT_FAILURE";

    const SUBSCRIPTION_PAYMENT = "SUBSCRIPTION_PAYMENT";

    const VOUCHER_PURCHASE = "VOUCHER_PURCHASE";
    const VOUCHER_REFUND = "VOUCHER_REFUND";

    const MERCHANT_PAYMENT = "MERCHANT_PAYMENT";

    const WITHDRAWAL_PAYMENT = "WITHDRAWAL_PAYMENT";
    const WITHDRAWAL_FAILURE = "WITHDRAWAL_FAILURE";

    const PAYMENT_FAILURE = "PAYMENT_FAILURE";

    const REFERRAL_INVITE = "REFERRAL_INVITE";
    const REFERRAL_JOINED = "REFERRAL_JOINED";

    const ERROR_ALERT = "ERROR_ALERT";
    const SP_REQUEST_FAILURE = "SP_REQUEST_FAILURE";
    const STATUS_UPDATE = "STATUS_UPDATE";
}
