runtime: custom
env: flex

# Ensure we skip ".env", which is only for local development
skip_files:
  - .git
#  - dist
#  - node_modules
#  - vendor
#  - ^"*.jar"

runtime_config:
  document_root: public
  enable_stackdriver_integration: true

env_variables:
  APP_NAME: Sidooh
  APP_KEY: base64:sAXxBMFFf2a4rlCKyJfsQdg/ks/AW4eGSVGpxDzY5A0=
  APP_ENV: production
  APP_LOG: errorlog
  APP_DEBUG: true
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  APP_TIMEZONE: Africa/Nairobi
  APP_URL: https://master-dot-hoodis3.uc.r.appspot.com


  CACHE_DRIVER: file
  SESSION_DRIVER: file

  DB_HOST: localhost
  DB_DATABASE: sidooh
  DB_USERNAME: root
  DB_PASSWORD: root
  DB_SOCKET: "/cloudsql/hoodis3:us-central1:hoodis"


  MAIL_MAILER: smtp
  MAIL_HOST: smtp.gmail.com
  MAIL_PORT: 465
  MAIL_USERNAME: sidserviceske@gmail.com
  MAIL_PASSWORD: dcmytgkrbgowqsiv
  MAIL_ENCRYPTION: ssl
  MAIL_FROM_ADDRESS: sidserviceske@gmail.com
  MAIL_FROM_NAME: "${APP_NAME}"

  MPESA_SANDBOX: false
  MPESA_BASE_URL: https://api.safaricom.co.ke/
  MPESA_KEY: wNhBKlqLR92dNwZjiSADOVnyZ98T29FS
  MPESA_SECRET: cta3bt2GYUCSuqGm
  MPESA_INITIATOR_SHORTCODE: 766148
  MPESA_STK_SHORTCODE: 766148
  MPESA_STK_PASS_KEY: 0323599173c3c91837a1c7a082ca14ac1bfdbf0d219c91000a1242b38980a40d

  MPESA_B2C_KEY: V5Jc8GFBsgo39c1nuvv7V4rqNlbLNkgX
  MPESA_B2C_SECRET: rGo3EtUUbak8dQUB
  MPESA_B2C_SHORTCODE: 3015319
  MPESA_B2C_INITIATOR: SidoohApi
  MPESA_B2C_MIN_AMOUNT: 10
  MPESA_B2C_MAX_AMOUNT: 70000
  MPESA_STK_MIN_AMOUNT: 10
  MPESA_STK_MAX_AMOUNT: 70000

  MPESA_ENV: production

  AT_API_KEY: 24f8a51e90338e4d2a6ebb81899fb4dc66099df456338be9da55cd8b5ce196f7
  AT_USERNAME: sandbox

  AT_SMS_API_KEY: a53e86bcf72ff0e103130e5442504410fdd6d0ef32827fd2794e3caefb92c191
  AT_SMS_USERNAME: sidooh_sms
  AT_SMS_FROM: Sidooh
  AT_AIRTIME_API_KEY: 89770c2faea7f33dce6ca5605a0cd7b9e810a999af8ea0c051a5e504d2380928
  AT_AIRTIME_USERNAME: sidooh_airtime

  AT_ENV: production

  TIMEZONE: Africa/Nairobi

  USSD_CODE: "*384*99#"

  SIDOOH_TAGLINE: "Sidooh, Makes You Money with Every Purchase."

  SENTRY_LARAVEL_DSN: https://127d0d5f0b19418d8fc3c9d16b44fd2b@o802918.ingest.sentry.io/5802789
  SENTRY_TRACES_SAMPLE_RATE: 1

  KYANDA_API_KEY: 04c83876101c48a4b083bf01812c2349
  KYANDA_MERCHANT_ID: sidooh


# Use the connection name obtained when configuring your Cloud SQL instance.
beta_settings:
  cloud_sql_instances: "hoodis3:us-central1:hoodis"

# App engine resources
manual_scaling:
  instances: 1
resources:
  #  cpu: 1.5
#  memory_gb: 2.5
#  disk_size_gb: 10

